# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22450f1e2be8b2fa77fed8903a6d4341963033f75727205fa228f6754fd2394c2dfeef769c7efa941483dcb18c7a0b92257bff3ac93d830fda24996b39ed72d1

test:
  secret_key_base: db04a6c51a2696b3c5f1e6e1dc97856150e728f744bcdd9d7d624fe5a65f33dec1a57f62b8e031651aa43adf90d5b5c8adac1d6fe1f55b69f947b6162871baff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
